version: "3"
services:
  db:
    image: postgres
    restart: always
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: test1234

  adminer:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - 8080:8080

  pgadmin:
    image: dpage/pgadmin4
#    links:
#      - db:postgres
#    volumes:
#      - ./pgadmin:/var/lib/pgadmin
    ports:
      - "80:80"
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: agiledots@gmail.com
      PGADMIN_DEFAULT_PASSWORD: test1234

